
name: Publish docs (Storybook) to GitHub Pages QA
on: 
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Deploy index.md for docs-qa site ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs-qa
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/docs-qa-index 
          clean: true 
          target-folder: docs
      - name: Generate Markdown file of links to branches
        working-directory: ./frontend/scripts
        run: | 
          gh api repos/ucsb-cs156-w22/demo-cra-customized/branches > branches.json
          node list-branches.mjs > ../storybook-qa-list/index.md
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs-qa
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/storybook-qa-list # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs/storybook-qa-list/
      - name: Install and Build ðŸ”§
        working-directory: ./frontend
        run: | # Install npm packages and build the Storybook files
          npm install
          mkdir -p storybook-static
          npm run build-storybook
      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@4.2.0
        with:
          repository-name: ${{ github.repository }}-docs-qa
          token: ${{ secrets.DOCS_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: frontend/storybook-static # The folder that the build-storybook script generates files.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs/storybook-qa/${{ github.head_ref}} # The folder that we serve our Storybook files from 
      
